import re


def separate_sentences(s: str) -> str:
    return re.sub(r'\.[ ]?', '\n', s)

def no_references(s: str) -> str:
    return re.sub(r'\[\d+\][ ]?', '', s)

def no_blanklines(s: str) -> str:
    return re.sub(r'\n[\n]+', '\n', s)

def no_tabs_or_whitespace(s: str) -> str:
    return re.sub(r'\t| ([ ]+)', '', s)


if __name__ == '__main__':
    dog = """The dog (Canis familiaris[4][5] or Canis lupus familiaris[5]) is a domesticated descendant of the wolf. Also called the domestic dog, it is derived from the extinct Pleistocene wolf,[6][7] and the modern wolf is the dog's nearest living relative.[8] Dogs were the first species to be domesticated[9][8] by hunter-gatherers over 15,000 years ago[7] before the development of agriculture.[1] Due to their long association with humans, dogs have expanded to a large number of domestic individuals[10] and gained the ability to thrive on a starch-rich diet that would be inadequate for other canids.[11]
The dog has been selectively bred over millennia for various behaviors, sensory capabilities, and physical attributes.[12] Dog breeds vary widely in shape, size, and color. They perform many roles for humans, such as hunting, herding, pulling loads, protection, assisting police and the military, companionship, therapy, and aiding disabled people. Over the millennia, dogs became uniquely adapted to human behavior, and the human-canine bond has been a topic of frequent study.[13] This influence on human society has given them the sobriquet of "man's best friend".[14]
In 1758, the Swedish botanist and zoologist Carl Linnaeus published in his Systema Naturae, the two-word naming of species (binomial nomenclature). Canis is the Latin word meaning "dog",[15] and under this genus, he listed the domestic dog, the wolf, and the golden jackal. He classified the domestic dog as Canis familiaris and, on the next page, classified the grey wolf as Canis lupus.[2] Linnaeus considered the dog to be a separate species from the wolf because of its upturning tail (cauda recurvata), which is not found in any other canid.[16]
In 1999, a study of mitochondrial DNA (mtDNA) indicated that the domestic dog may have originated from the grey wolf, with the dingo and New Guinea singing dog breeds having developed at a time when human communities were more isolated from each other.[17] In the third edition of Mammal Species of the World published in 2005, the mammalogist W. Christopher Wozencraft listed under the wolf Canis lupus its wild subspecies and proposed two additional subspecies, which formed the domestic dog clade: familiaris, as named by Linnaeus in 1758 and, dingo named by Meyer in 1793. Wozencraft included hallstromi (the New Guinea singing dog) as another name (junior synonym) for the dingo. Wozencraft referred to the mtDNA study as one of the guides informing his decision.[3] Mammalogists have noted the inclusion of familiaris and dingo together under the "domestic dog" clade[18] with some debating it.[19]
In 2019, a workshop hosted by the IUCN/Species Survival Commission's Canid Specialist Group considered the dingo and the New Guinea singing dog to be feral Canis familiaris and therefore did not assess them for the IUCN Red List of Threatened Species.[4]
The Cretaceous-Paleogene extinction event occurred 66 million years ago and brought an end to the non-avian dinosaurs and the appearance of the first carnivorans.[20] The name carnivoran is given to a member of the order Carnivora. Carnivorans possess a common arrangement of teeth called carnassials, in which the first lower molar and the last upper premolar possess blade-like enamel crowns that act similar to a pair of shears for cutting meat. This dental arrangement has been modified by adaptation over the past 60 million years for diets composed of meat, for crushing vegetation, or for the loss of the carnassial function altogether as in seals, sea lions, and walruses. Today, not all carnivorans are carnivores, such as the insect-eating aardwolf.[5]
The carnivoran ancestors of the dog-like caniforms and the cat-like feliforms began their separate evolutionary paths just after the end of the dinosaurs. The first members of the dog family Canidae appeared 40 million years ago,[21] of which only its subfamily the Caninae survives today in the form of the wolf-like and fox-like canines. Within the Caninae, the first members of genus Canis appeared six million years ago,[15] the ancestors of modern domestic dogs, wolves, coyotes, and golden jackals.
The earliest remains generally accepted to be those of a domesticated dog were discovered in Bonn-Oberkassel, Germany. Contextual, isotopic, genetic, and morphological evidence shows that this dog was not a local wolf.[22] The dog was dated to 14,223 years ago and was found buried along with a man and a woman, all three having been sprayed with red hematite powder and buried under large, thick basalt blocks. The dog had died of canine distemper.[23] Earlier remains dating back to 30,000 years ago have been described as Paleolithic dogs, but their status as dogs or wolves remains debated[24] because considerable morphological diversity existed among wolves during the Late Pleistocene.[1]
This timing indicates that the dog was the first species to be domesticated[9][8] in the time of hunter-gatherers,[7] which predates agriculture.[1] DNA sequences show that all ancient and modern dogs share a common ancestry and descended from an ancient, extinct wolf population which was distinct from the modern wolf lineage.[6][7] Most dogs form a sister group to the remains of a Late Pleistocene wolf found in the Kessleroch cave near Thayngen in the canton of Schaffhausen, Switzerland, which dates to 14,500 years ago. The most recent common ancestor of both is estimated to be from 32,100 years ago.[25] This indicates that an extinct Late Pleistocene wolf may have been the ancestor of the dog,[8][1][26] with the modern wolf being the dog's nearest living relative.[8]
The dog is a classic example of a domestic animal that likely travelled a commensal pathway into domestication.[24][27] The questions of when and where dogs were first domesticated have taxed geneticists and archaeologists for decades.[9] Genetic studies suggest a domestication process commencing over 25,000 years ago, in one or several wolf populations in either Europe, the high Arctic, or eastern Asia.[10] In 2021, a literature review of the current evidence infers that the dog was domesticated in Siberia 23,000 years ago by ancient North Siberians, then later dispersed eastward into the Americas and westward across Eurasia.[22] 
Dogs are the most variable mammal on earth with around 450 globally recognized dog breeds.[10] In the Victorian era, directed human selection developed the modern dog breeds, which resulted in a vast range of phenotypes.[8] Most breeds were derived from small numbers of founders within the last 200 years,[8][10] and since then dogs have undergone rapid phenotypic change and were formed into today's modern breeds due to artificial selection imposed by humans. The skull, body, and limb proportions vary significantly between breeds, with dogs displaying more phenotypic diversity than can be found within the entire order of carnivores. These breeds possess distinct traits related to morphology, which include body size, skull shape, tail phenotype, fur type and colour.[8] Their behavioural traits include guarding, herding, and hunting,[8] retrieving, and scent detection. Their personality traits include hypersocial behavior, boldness, and aggression,[10] which demonstrates the functional and behavioral diversity of dogs.[8] As a result, present day dogs are the most abundant carnivore species and are dispersed around the world.[10] The most striking example of this dispersal is that of the numerous modern breeds of European lineage during the Victorian era.[7]
All healthy dogs, regardless of their size and type, have an identical skeletal structure with the exception of the number of bones in the tail, although there is significant skeletal variation between dogs of different types.[28][29] The dog's skeleton is well adapted for running; the vertebrae on the neck and back have extensions for powerful back muscles to connect to, the long ribs provide plenty of room for the heart and lungs, and the shoulders are unattached to the skeleton allowing great flexibility.[28][29]
Compared to the dog's wolf-like ancestors, selective breeding since domestication has seen the dog's skeleton greatly enhanced in size for larger types as mastiffs and miniaturised for smaller types such as terriers; dwarfism has been selectively utilised for some types where short legs are advantageous such as dachshunds and corgis.[29] Most dogs naturally have 26 vertebrae in their tails, but some with naturally short tails have as few as three.[28]
The dog's skull has identical components regardless of breed type, but there is significant divergence in terms of skull shape between types.[29][30] The three basic skull shapes are the elongated dolichocephalic type as seen in sighthounds, the intermediate mesocephalic or mesaticephalic type, and the very short and broad brachycephalic type exemplified by mastiff type skulls.[29][30] 
A dog's senses include vision, hearing, smell, taste, touch. One study suggested that dogs can feel Earth's magnetic field.[31]
The coats of domestic dogs are of two varieties: "double" being familiar with dogs (as well as wolves) originating from colder climates, made up of a coarse guard hair and a soft down hair, or "single", with the topcoat only. Breeds may have an occasional "blaze", stripe, or "star" of white fur on their chest or underside.[32] Premature graying can occur in dogs from as early as one year of age; this is associated with impulsive behaviors, anxiety behaviors, fear of noise, and fear of unfamiliar people or animals.[33]
There are many different shapes for dog tails: straight, straight up, sickle, curled, or corkscrew. As with many canids, one of the primary functions of a dog's tail is to communicate their emotional state, which can be crucial in getting along with others. In some hunting dogs the tail is traditionally docked to avoid injuries. 
Some breeds of dogs are prone to specific genetic ailments such as elbow and hip dysplasia, blindness, deafness, pulmonic stenosis, cleft palate, and trick knees. Two severe medical conditions significantly affecting dogs are pyometra, affecting unspayed females of all breeds and ages, and Gastric dilatation volvulus (bloat), which affects larger breeds or deep-chested dogs. Both of these are acute conditions and can kill rapidly. Dogs are also susceptible to parasites such as fleas, ticks, mites, hookworms, tapeworms, roundworms, and heartworms, which is a roundworm species that lives in the hearts of dogs.
Several human foods and household ingestible are toxic to dogs, including chocolate solids, causing theobromine poisoning, onions and garlic, causing thiosulphate, sulfoxide or disulfide poisoning, grapes and raisins, macadamia nuts, and xylitol.[34] The nicotine in tobacco can also be dangerous to dogs. Signs of ingestion can include copious vomiting (e.g., from eating cigar butts) or diarrhea. Some other symptoms are abdominal pain, loss of coordination, collapse, or death.[35][page needed]
Dogs are also vulnerable to some of the same health conditions as humans, including diabetes, dental and heart disease, epilepsy, cancer, hypothyroidism, and arthritis. 
The typical lifespan of dogs varies widely among breeds, but for most, the median longevity (the age at which half the dogs in a population have died and half are still alive) ranges from 10 to 13 years.[36][37] The median longevity of mixed-breed dogs, taken as an average of all sizes, is one or more years longer than that of purebred dogs when all breeds are averaged.[36][37][38] For dogs in England, increased body weight has been found to be negatively correlated with longevity (i.e., the heavier the dog, the shorter its lifespan), and mixed-breed dogs live on average 1.2 years longer than purebred dogs.[39]
In domestic dogs, sexual maturity happens around six months to one year for both males and females, although this can be delayed until up to two years of age for some large breeds, and is the time at which female dogs will have their first estrous cycle. They will experience subsequent estrous cycles semiannually, during which the body prepares for pregnancy. At the peak of the cycle, females will become estrous, mentally and physically receptive to copulation. Because the ova survive and can be fertilized for a week after ovulation, more than one male can sire the same litter.[12]
Fertilization typically occurs two to five days after ovulation; 14-16 days after ovulation, the embryo attaches to the uterus and after seven to eight more days, a heartbeat is detectable.[40][41]
Dogs bear their litters roughly 58 to 68 days after fertilization,[12][42] with an average of 63 days, although the length of gestation can vary. An average litter consists of about six puppies.[43]
Neutering is the sterilization of animals, usually by removing the male's testicles or the female's ovaries and uterus, to eliminate the ability to procreate and reduce sex drive. Because of dogs' overpopulation in some countries, many animal control agencies, such as the American Society for the Prevention of Cruelty to Animals (ASPCA), advise that dogs not intended for further breeding should be neutered, so that they do not have undesired puppies that may later be euthanized.[44]
According to the Humane Society of the United States, three to four million dogs and cats are euthanized each year.[45] Many more are confined to cages in shelters because there are many more animals than there are homes. Spaying or castrating dogs helps keep overpopulation down.[46]
Neutering reduces problems caused by hypersexuality, especially in male dogs.[47] Spayed female dogs are less likely to develop cancers affecting the mammary glands, ovaries, and other reproductive organs.[48][page needed] However, neutering increases the risk of urinary incontinence in female dogs[49] and prostate cancer in males[50] and osteosarcoma, hemangiosarcoma, cruciate ligament rupture, obesity, and diabetes mellitus in either sex.[51] 
A common breeding practice for pet dogs is mating between close relatives (e.g., between half and full siblings).[52] Inbreeding depression is considered to be due mainly to the expression of homozygous deleterious recessive mutations.[53] Outcrossing between unrelated individuals, including dogs of different breeds, results in the beneficial masking of deleterious recessive mutations in progeny.[54]
In a study of seven dog breeds (the Bernese Mountain Dog, Basset Hound, Cairn Terrier, Brittany, German Shepherd Dog, Leonberger, and West Highland White Terrier), it was found that inbreeding decreases litter size and survival.[55] Another analysis of data on 42,855 Dachshund litters found that as the inbreeding coefficient increased, litter size decreased and the percentage of stillborn puppies increased, thus indicating inbreeding depression.[56] In a study of Boxer litters, 22% of puppies died before reaching 7 weeks of age. Stillbirth was the most frequent cause of death, followed by infection. Mortality due to infection increased significantly with increases in inbreeding.[57] 
"""
    
    print('Wikipedia')
    print(
        no_blanklines(
        no_references(
        separate_sentences(
        dog))))
    print('q!')
